# -*- coding: utf-8 -*-
"""modelbuilding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOFpOcl3LaV7srAmWba0cPb2L3_fJqGY
"""

import pandas as pd


df = pd.read_csv("Salary_Data.csv")

df

df.isnull().sum()

"""### Identifying Duplicate Rows

Let's check for duplicate rows in the entire DataFrame. This will help us understand if there are any entries that are exact copies of others across all columns.
"""

# Find duplicate rows
duplicate_rows = df[df.duplicated()]

# Display the number of duplicate rows found
print(f"Number of duplicate rows found: {len(duplicate_rows)}")

# Display the duplicate rows
if not duplicate_rows.empty:
    print("\nDuplicate Rows (first 5 shown if many):")
    print(duplicate_rows.head())
else:
    print("No duplicate rows found in the DataFrame.")

"""### Removing Duplicate Rows

Now that we've identified the duplicate rows, let's remove them from the DataFrame to ensure data integrity and avoid skewed analysis. We'll keep the first occurrence of each duplicate.
"""

# Remove duplicate rows, keeping the first occurrence
df_cleaned = df.drop_duplicates(keep='first')

# Display the number of rows after removal
print(f"Number of rows after removing duplicates: {len(df_cleaned)}")

# Display the new shape of the DataFrame
print(f"New DataFrame shape: {df_cleaned.shape}")

"""### Label Encoding Categorical Features

Now, let's identify the categorical columns in `df_cleaned` and apply label encoding to convert them into a numerical format. This is a common preprocessing step for many machine learning models.
"""

from sklearn.preprocessing import LabelEncoder

# Make a copy to avoid SettingWithCopyWarning
df_encoded = df_cleaned.copy()

# Identify categorical columns
categorical_cols = ['Gender', 'Education Level', 'Job Title']

# Apply Label Encoding to each categorical column
for col in categorical_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col])
    print(f"LabelEncoder fitted for column: {col}")

print("\nDataFrame after Label Encoding:")
print(df_encoded.head())

"""### Separating Dependent and Independent Variables

Now, let's separate our dataset into features (independent variables) and the target (dependent variable). In this case, 'Salary' will be our target variable `y`, and all other columns will be our features `X`.
"""

# Define features (X) and target (y)
X = df_encoded.drop('Salary', axis=1)
y = df_encoded['Salary']

print("Independent variables (X):")
display(X.head())

print("\nDependent variable (y):")
display(y.head())

"""### Handling Missing Values

Now, let's address the missing values in our `df_encoded` DataFrame. We will impute numerical columns with their mean and (encoded) categorical columns with their mode to ensure data completeness for modeling.
"""

# Check for null values in df_encoded
print("Null values before imputation:")
display(df_encoded.isnull().sum())

# Impute numerical columns with the mean
for col in ['Age', 'Years of Experience', 'Salary']:
    if df_encoded[col].isnull().any():
        df_encoded[col] = df_encoded[col].fillna(df_encoded[col].mean())
        print(f"Imputed '{col}' with mean.")

# Impute encoded categorical columns with the mode
for col in ['Gender', 'Education Level', 'Job Title']:
    if df_encoded[col].isnull().any():
        df_encoded[col] = df_encoded[col].fillna(df_encoded[col].mode()[0])
        print(f"Imputed '{col}' with mode.")

print("\nNull values after imputation:")
display(df_encoded.isnull().sum())

print("\nDataFrame after imputation (first 5 rows):")
display(df_encoded.head())

"""### Model Training and Evaluation

Now that our data is clean and prepared, we will proceed with training several regression models. We'll split the data into training and testing sets, train each model, make predictions, and evaluate their performance using metrics such as Mean Absolute Error (MAE), Mean Squared Error (MSE), and R-squared.
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Re-define features (X) and target (y) from the imputed df_encoded
X = df_encoded.drop('Salary', axis=1)
y = df_encoded['Salary']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {len(X_train)} samples")
print(f"Testing set size: {len(X_test)} samples")

"""#### 1. Linear Regression

Let's start with a simple Linear Regression model.
"""

# Initialize and train the Linear Regression model
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

# Make predictions
y_pred_lin_reg = lin_reg.predict(X_test)

# Evaluate the model
mae_lin_reg = mean_absolute_error(y_test, y_pred_lin_reg)
mse_lin_reg = mean_squared_error(y_test, y_pred_lin_reg)
r2_lin_reg = r2_score(y_test, y_pred_lin_reg)

print(f"Linear Regression - MAE: {mae_lin_reg:.2f}")
print(f"Linear Regression - MSE: {mse_lin_reg:.2f}")
print(f"Linear Regression - R-squared: {r2_lin_reg:.2f}")

"""#### 2. Decision Tree Regressor

Next, we'll train a Decision Tree Regressor.
"""

# Initialize and train the Decision Tree Regressor model
dec_tree_reg = DecisionTreeRegressor(random_state=42)
dec_tree_reg.fit(X_train, y_train)

# Make predictions
y_pred_dec_tree = dec_tree_reg.predict(X_test)

# Evaluate the model
mae_dec_tree = mean_absolute_error(y_test, y_pred_dec_tree)
mse_dec_tree = mean_squared_error(y_test, y_pred_dec_tree)
r2_dec_tree = r2_score(y_test, y_pred_dec_tree)

print(f"Decision Tree Regressor - MAE: {mae_dec_tree:.2f}")
print(f"Decision Tree Regressor - MSE: {mse_dec_tree:.2f}")
print(f"Decision Tree Regressor - R-squared: {r2_dec_tree:.2f}")

"""#### 3. Random Forest Regressor

Now, let's use an ensemble method: Random Forest Regressor.
"""

# Initialize and train the Random Forest Regressor model
rand_forest_reg = RandomForestRegressor(random_state=42)
rand_forest_reg.fit(X_train, y_train)

# Make predictions
y_pred_rand_forest = rand_forest_reg.predict(X_test)

# Evaluate the model
mae_rand_forest = mean_absolute_error(y_test, y_pred_rand_forest)
mse_rand_forest = mean_squared_error(y_test, y_pred_rand_forest)
r2_rand_forest = r2_score(y_test, y_pred_rand_forest)

print(f"Random Forest Regressor - MAE: {mae_rand_forest:.2f}")
print(f"Random Forest Regressor - MSE: {mse_rand_forest:.2f}")
print(f"Random Forest Regressor - R-squared: {r2_rand_forest:.2f}")

"""#### 4. Support Vector Machine (SVM) Regressor

We will now train a Support Vector Machine (SVR) model. Note that SVR can be computationally intensive and might require scaling for optimal performance, but we'll try it directly first.
"""

from sklearn.preprocessing import StandardScaler

# Scale the data for SVR
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train_scaled = scaler_X.fit_transform(X_train)
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).flatten()
X_test_scaled = scaler_X.transform(X_test)

# Initialize and train the SVR model
svr_reg = SVR(kernel='rbf') # Using RBF kernel as a common choice
svr_reg.fit(X_train_scaled, y_train_scaled)

# Make predictions and inverse transform to original scale
y_pred_svr_scaled = svr_reg.predict(X_test_scaled)
y_pred_svr = scaler_y.inverse_transform(y_pred_svr_scaled.reshape(-1, 1)).flatten()

# Evaluate the model
mae_svr = mean_absolute_error(y_test, y_pred_svr)
mse_svr = mean_squared_error(y_test, y_pred_svr)
r2_svr = r2_score(y_test, y_pred_svr)

print(f"SVR - MAE: {mae_svr:.2f}")
print(f"SVR - MSE: {mse_svr:.2f}")
print(f"SVR - R-squared: {r2_svr:.2f}")

"""#### 5. K-Nearest Neighbors (KNN) Regressor

Finally, let's train a K-Nearest Neighbors (KNN) Regressor. KNN can also benefit from scaling.
"""

# Using the same scaled data from SVR for KNN

# Initialize and train the KNN Regressor model
knn_reg = KNeighborsRegressor(n_neighbors=5) # n_neighbors can be tuned
knn_reg.fit(X_train_scaled, y_train_scaled)

# Make predictions and inverse transform to original scale
y_pred_knn_scaled = knn_reg.predict(X_test_scaled)
y_pred_knn = scaler_y.inverse_transform(y_pred_knn_scaled.reshape(-1, 1)).flatten()

# Evaluate the model
mae_knn = mean_absolute_error(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print(f"KNN Regressor - MAE: {mae_knn:.2f}")
print(f"KNN Regressor - MSE: {mse_knn:.2f}")
print(f"KNN Regressor - R-squared: {r2_knn:.2f}")

"""### Visualizing Model Performance

Now that all models are trained and evaluated, let's visualize their performance metrics (Mean Absolute Error, Mean Squared Error, and R-squared) to easily compare which model performed best.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Collect the performance metrics
model_performance = pd.DataFrame({
    'Model': ['Linear Regression', 'Decision Tree', 'Random Forest', 'SVR', 'KNN Regressor'],
    'MAE': [mae_lin_reg, mae_dec_tree, mae_rand_forest, mae_svr, mae_knn],
    'MSE': [mse_lin_reg, mse_dec_tree, mse_rand_forest, mse_svr, mse_knn],
    'R-squared': [r2_lin_reg, r2_dec_tree, r2_rand_forest, r2_svr, r2_knn]
})

# Display the performance table
print("Model Performance Summary:")
display(model_performance.sort_values(by='R-squared', ascending=False))

# Plotting MAE
plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='MAE', data=model_performance, hue='Model', palette='viridis', legend=False)
plt.title('Comparison of Mean Absolute Error (MAE) Across Models')
plt.ylabel('Mean Absolute Error')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Plotting MSE
plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='MSE', data=model_performance, hue='Model', palette='plasma', legend=False)
plt.title('Comparison of Mean Squared Error (MSE) Across Models')
plt.ylabel('Mean Squared Error')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Plotting R-squared
plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='R-squared', data=model_performance, hue='Model', palette='magma', legend=False)
plt.title('Comparison of R-squared Across Models')
plt.ylabel('R-squared Score')
plt.ylim(0, 1) # R-squared typically ranges from 0 to 1
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""### Performance Summary

Based on the visualizations and the summary table:

*   **Random Forest Regressor** consistently shows the best performance with the lowest MAE and MSE, and the highest R-squared score.
*   **Decision Tree Regressor** and **KNN Regressor** also perform reasonably well, often better than Linear Regression and SVR.
*   **Linear Regression** generally has the highest errors (MAE, MSE) and the lowest R-squared, indicating it's the least accurate among the models for this dataset.

This analysis suggests that ensemble methods like Random Forest are highly effective for this dataset.
"""

import pickle

# Save the best performing model (Random Forest Regressor)
model_filename = 'random_forest_model.pkl'
with open(model_filename, 'wb') as file:
    pickle.dump(rand_forest_reg, file)

print(f"Best model (Random Forest Regressor) saved to {model_filename}")
